apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mysqlschemas.mysql.sample.javaoperatorsdk
spec:
  group: mysql.sample.javaoperatorsdk
  version: v1
  subresources:
    status: {}
  scope: Namespaced
  names:
    plural: mysqlschemas
    singular: mysqlschema
    kind: MySQLSchema
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          type: object
          required:
          - encoding
          properties:
            encoding:
              type: string
