apiVersion: v1
kind: Namespace
metadata:
  name: mysql-schema
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-schema-operator
  namespace: mysql-schema
spec:
  selector:
    matchLabels:
      app: mysql-schema-operator
  replicas: 1 # we always run a single replica of the operator to avoid duplicate handling of events
  strategy:
    type: Recreate # during an upgrade the operator will shut down before the new version comes up to prevent two instances running at the same time
  template:
    metadata:
      labels:
        app: mysql-schema-operator
    spec:
      serviceAccount: mysql-schema-operator # specify the ServiceAccount under which's RBAC persmissions the operator will be executed under
      containers:
      - name: operator
        image: mswiderski/mysql-operator:0.0.0-SNAPSHOT
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: MYSQL_HOST
          value: mysql.mysql # assuming the MySQL server runs in a namespace called "mysql" on Kubernetes
        - name: MYSQL_USER
          value: root
        - name: MYSQL_PASSWORD
          value: password # sample-level security
        - name: QUARKUS_LAUNCH_DEVMODE
          value: 'false' # to allow deployment in development mode

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mysql-schema-operator
  namespace: mysql-schema

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: mysql-schema-operator
rules:
- apiGroups:
  - mysql.sample.javaoperatorsdk
  resources:
  - mysqlschemas
  verbs:
  - "*"
- apiGroups:
  - mysql.sample.javaoperatorsdk
  resources:
  - mysqlschemas/status
  verbs:
  - "*"
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - "get"
  - "list"
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - "*"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mysql-schema-operator
subjects:
- kind: ServiceAccount
  name: mysql-schema-operator
  namespace: mysql-schema
roleRef:
  kind: ClusterRole
  name: mysql-schema-operator
  apiGroup: ""
